feat(cli): introduce new --last flag, to stop recommending HEAD~1 (#3916)
* test(cli): add regression test

* feat(cli): implement new `--last` CLI flag

The upgrade of ES2017 to ES2022 is because of the use of
`Object.hasOwn` API which is less ugly than hardcoding
`undefined`.

* docs(ci): stop recommending HEAD~1

In a single-commit repo, this would lead to this error:

```
Error: fatal: ambiguous argument 'HEAD~1..HEAD': unknown revision
or path not in the working tree.
```

Now that we have the `--last` flag, this should work for the case
in which we want just to analyze the last commit, not specify a
range of commits via `--from` and `--to`.

Closes https://github.com/conventional-changelog/commitlint/pull/3892

* fix: use --pretty=format:"%B" instead of --pretty=%B

The latter adds unnecessary whitespace at the end of the commit
msg.

---------

Co-authored-by: Mehrshad <code.rezaei@gmail.com>